package com.github.iTzhsnu.WynnSearcher.builder.skilltree;

public enum SkillEnum {
    //ANY
    PROFICIENCY_1,
    PROFICIENCY_2,
    CHEAPER_1ST_SP_COST,
    CHEAPER_3RD_SP_COST,
    CHEAPER_1ST_SP_COST_1,
    CHEAPER_2ND_SP_COST_1,
    CHEAPER_3RD_SP_COST_1,
    CHEAPER_4TH_SP_COST_1,
    CHEAPER_1ST_SP_COST_2,
    CHEAPER_2ND_SP_COST_2,
    CHEAPER_3RD_SP_COST_2,
    CHEAPER_4TH_SP_COST_2,
    EARTH_DAMAGE,
    THUNDER_DAMAGE,
    WATER_DAMAGE,
    FIRE_DAMAGE,
    AIR_DAMAGE,
    PRECISE_STRIKES,

    //WARRIOR
    BASH,
    DOUBLE_BASH,
    CHARGE,
    VEHEMENT,
    TOUGHER_SKIN,
    UPPERCUT,
    WAR_SCREAM,
    HEAVY_IMPACT,
    QUADRUPLE_BASH,
    FIREWORKS,
    FLYBY_JAB,
    FLAMING_UPPERCUT,
    HALF_MOON_SWIPE,
    IRON_LUNGS,
    COUNTER,
    GENERALIST,
    MANTLE_OF_THE_BOVEMISTS,
    BAKALS_GRASP,
    AERODYNAMICS,
    PROVOKE,
    AIR_SHOUT,
    ENRAGED_BLOW,
    FLYING_KICK,
    STRONGER_MANTLE,
    MANACHISM,
    BOILING_BLOOD,
    RAGNAROKKR,
    AMBIDEXTROUS,
    BURNING_HEART,
    STRONGER_BASH,
    INTOXICATING_BLOOD,
    COLLIDE,
    REJUVENATING_SKIN,
    COMET,
    UNCONTAINABLE_CORRUPTION,
    RADIANT_DEVOTEE,
    WHIRLWIND_STRIKE,
    MYTHRIL_SKIN,
    ARMOUR_BREAKER,
    SHIELD_STRIKE,
    SPARKLING_HOPE,
    MASSIVE_BASH,
    TEMPEST,
    SPIRIT_OF_THE_RABBIT,
    MASSACRE,
    AXE_KICK,
    RADIANCE,
    DISCOMBOBULATE,
    CYCLONE,
    THUNDERCLAP,
    SECOND_CHANCE,
    BLOOD_PACT,
    HAEMORRHAGE,
    BRINK_OF_MADNESS,
    MARTYR,


    //ASSASSIN



    //ARCHER
    ARROW_BOMB,
    HEART_SHATTER,


    //MAGE


    //SHAMAN


}
