package com.github.iTzhsnu.WynnSearcher.builder.skilltree;

public enum SkillEnum {
    //ANY
    PROFICIENCY_1,
    PROFICIENCY_2,
    REDUCE_10_1ST_SP_COST,
    REDUCE_10_3RD_SP_COST,
    REDUCE_5_1ST_SP_COST,
    REDUCE_5_2ND_SP_COST,
    REDUCE_5_3RD_SP_COST,
    REDUCE_5_4TH_SP_COST,
    EARTH_DAMAGE,
    THUNDER_DAMAGE,
    WATER_DAMAGE,
    FIRE_DAMAGE,
    AIR_DAMAGE,
    PRECISE_STRIKES,

    //WARRIOR
    BASH,
    DOUBLE_BASH,
    CHARGE,
    VEHEMENT,
    TOUGHER_SKIN,
    UPPERCUT,
    WAR_SCREAM,
    HEAVY_IMPACT,
    QUADRUPLE_BASH,
    FIREWORKS,
    FLYBY_JAB,
    FLAMING_UPPERCUT,
    HALF_MOON_SWIPE,
    IRON_LUNGS,
    COUNTER,
    GENERALIST,
    MANTLE_OF_THE_BOVEMISTS,
    BAKALS_GRASP,
    AERODYNAMICS,
    PROVOKE,
    AIR_SHOUT,
    ENRAGED_BLOW,
    FLYING_KICK,
    STRONGER_MANTLE,
    MANACHISM,
    BOILING_BLOOD,
    RAGNAROKKR,
    AMBIDEXTROUS,
    BURNING_HEART,
    STRONGER_BASH,
    INTOXICATING_BLOOD,
    COLLIDE,
    REJUVENATING_SKIN,
    COMET,


    //ASSASSIN



    //ARCHER
    ARROW_BOMB,
    HEART_SHATTER,


    //MAGE


    //SHAMAN


}
